POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email":"example@gmail.com",
    "password":"asempaH@.COMEW"
}

### Find a particular user with a given ID

GET http://localhost:3000/auth/5

### Delete a user
DELETE http://localhost:3000/auth/1

### Update a user
PATCH http://localhost:3000/auth/1